GET http://localhost:5555/discussion/

###

GET http://localhost:5555/discussion/discussion/1/get/

###

POST http://localhost:5555/discussion/create/
Accept: application/json
Content-Type: application/json

{
    "name": "nametestsoutenance2",
    "users": ["userstestsoutenance2", "userstestsoutenance3"]
}

###

PUT http://localhost:5555/discussion/3/update/
Accept: application/json
Content-Type: application/json

{
    "name": "discussiontest6updated",
    "users": ["userstest6updated"]
}

###

DELETE http://localhost:5555/discussion/6/delete/